# Generated by Django 4.2.16 on 2026-04-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_specialist_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('BLUEPRINT', 'Blueprint'), ('ARCHIVED', 'Arquivado'), ('SUSPENDED', 'Suspenso')], default='ACTIVE', max_length=20),
        ),
    ]
