# Generated by Django 4.2.16 on 2026-04-18 14:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data_confidentiality',
            field=models.CharField(choices=[('Corporativo', 'Corporativo'), ('Dominio', 'Dominio'), ('Subdominio', 'Subdominio'), ('Confidencial', 'Confidencial'), ('Altamente Restrito', 'Altamente Restrito')], default='Corporativo', max_length=100, verbose_name='Confidencialidade dos Dados'),
        ),
        migrations.CreateModel(
            name='DataSubDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Subdomínio')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', to='projects.datadomain', verbose_name='Domínio Pai')),
            ],
            options={
                'verbose_name': 'Subdomínio de Dados',
                'verbose_name_plural': 'Subdomínios de Dados',
                'db_table': 'data_subdomains',
                'unique_together': {('domain', 'name')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='subdomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.datasubdomain', verbose_name='Subdomínio de Dados'),
        ),
    ]
