# Generated by Django 4.2.16 on 2026-04-18 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_data_confidentiality_datasubdomain_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datadomain',
            options={'ordering': ['name'], 'verbose_name': 'Domínio de Dados', 'verbose_name_plural': 'Domínios de Dados'},
        ),
        migrations.AlterModelOptions(
            name='datasubdomain',
            options={'ordering': ['name'], 'verbose_name': 'Subdomínio de Dados', 'verbose_name_plural': 'Subdomínios de Dados'},
        ),
    ]
