# Generated by Django 4.2.16 on 2026-04-10 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_specialist_prompt'),
        ('dashboards', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('governance', '0005_agentsystemprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(help_text='Descrição estruturada dos objetivos, KPIs e widgets do dashboard.', verbose_name='Conteúdo do Prompt')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_prompts_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_prompts', to='projects.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Prompt de Relatório',
                'verbose_name_plural': 'Prompts de Relatório',
                'db_table': 'governance_report_prompts',
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WidgetScriptBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('widget_id', models.CharField(help_text='ID único do widget no JSON de configuração do dashboard.', max_length=100, verbose_name='ID do Widget')),
                ('prompt', models.TextField(help_text='Instrução específica para este componente.', verbose_name='Prompt do Widget')),
                ('script_type', models.CharField(choices=[('SQL', 'SQL Query'), ('PYTHON', 'Python/Pandas Script')], default='SQL', max_length=20)),
                ('script_content', models.TextField(help_text='SQL ou código Python que gera os dados deste widget.', verbose_name='Conteúdo do Script')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_bindings', to='dashboards.dashboard', verbose_name='Dashboard')),
            ],
            options={
                'verbose_name': 'Binding de Script de Widget',
                'verbose_name_plural': 'Bindings de Scripts de Widgets',
                'db_table': 'governance_widget_scripts',
                'ordering': ['-version', 'widget_id'],
                'unique_together': {('dashboard', 'widget_id', 'version')},
            },
        ),
    ]
