# Generated by Django 4.2.16 on 2026-04-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0006_reportprompt_widgetscriptbinding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalSystemPrompt',
        ),
    ]
