# Generated by Django 4.2.16 on 2026-04-14 18:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('governance', '0007_delete_globalsystemprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAIConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('persona_title', models.CharField(default='Analista Financeiro Sênior', max_length=255, verbose_name='Título da Persona')),
                ('persona_description', models.TextField(default='Você é um analista financeiro sênior especializado em identificar relações ocultas em dados e gerar insights estratégicos.', verbose_name='Descrição da Persona')),
                ('temperature', models.FloatField(default=0.3, verbose_name='Temperatura')),
                ('top_p', models.FloatField(default=0.9, verbose_name='Top P')),
                ('top_k', models.IntegerField(default=250, verbose_name='Top K')),
                ('max_tokens_limit', models.IntegerField(default=32000, verbose_name='Limite de Tokens')),
                ('ingestion_row_limit', models.IntegerField(default=5000, verbose_name='Limite de Ingestão (Linhas)')),
                ('compliance_rules', models.TextField(blank=True, verbose_name='Diretrizes de Compliance')),
                ('language', models.CharField(default='pt-BR', max_length=10, verbose_name='Idioma')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_configs', to='users.tenant')),
            ],
            options={
                'verbose_name': 'Configuração Global de IA',
                'verbose_name_plural': 'Configurações Globais de IA',
                'db_table': 'governance_global_config',
            },
        ),
    ]
