# Generated by Django 4.2.16 on 2026-04-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0008_globalaiconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalaiconfig',
            name='session_timeout_minutes',
            field=models.IntegerField(default=15, verbose_name='Timeout de Sessão (min)'),
        ),
    ]
