# Generated by Django 4.2.16 on 2026-04-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0009_globalaiconfig_session_timeout_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalaiconfig',
            name='pii_keywords_json',
            field=models.JSONField(blank=True, default=dict, help_text="JSON com palavras-chave e estratégias de máscara (Ex: {'nome': 'MASK_NAME'})", verbose_name='Dicionário de PII (Anonimização)'),
        ),
    ]
