# Generated by Django 4.2.16 on 2026-04-10 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0006_reportprompt_widgetscriptbinding'),
        ('dashboards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='report_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboards', to='governance.reportprompt', verbose_name='Prompt de Relatório'),
        ),
    ]
