# Generated by Django 4.2.16 on 2026-04-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='html_content',
            field=models.TextField(blank=True, help_text='Snapshot completo do HTML gerado para esta versão', verbose_name='Conteúdo HTML'),
        ),
    ]
