# Generated by Django 4.2.16 on 2026-04-15 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reports_generated_count', models.PositiveIntegerField(default=0, verbose_name='Relatórios Gerados (Mês Atual)')),
                ('max_reports_per_month', models.PositiveIntegerField(default=10, verbose_name='Limite de Relatórios/Mês')),
                ('reset_date', models.DateField(auto_now_add=True, verbose_name='Data de Reinício')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Quota de Uso',
                'verbose_name_plural': 'Quotas de Uso',
                'db_table': 'user_usage_quotas',
            },
        ),
    ]
