# Generated by Django 4.2.16 on 2026-04-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usagequota'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagequota',
            name='input_tokens_count',
            field=models.BigIntegerField(default=0, verbose_name='Tokens de Entrada (Mês Atual)'),
        ),
        migrations.AddField(
            model_name='usagequota',
            name='max_tokens_monthly_limit',
            field=models.BigIntegerField(default=500000, verbose_name='Limite mensal de Tokens'),
        ),
        migrations.AddField(
            model_name='usagequota',
            name='output_tokens_count',
            field=models.BigIntegerField(default=0, verbose_name='Tokens de Saída (Mês Atual)'),
        ),
    ]
