# Generated by Django 4.2.16 on 2026-04-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usagequota_input_tokens_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagequota',
            name='max_logins_limit',
            field=models.PositiveIntegerField(default=100, verbose_name='Limite Total de Logins'),
        ),
        migrations.AddField(
            model_name='usagequota',
            name='total_logins_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Contador Total de Logins'),
        ),
    ]
