# Generated by Django 4.2.16 on 2026-04-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_add_execution_trace'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiontrace',
            name='project_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='ID do domínio de dados (Projeto)', null=True),
        ),
        migrations.AddField(
            model_name='executiontrace',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='ID do usuário que iniciou a tarefa', null=True),
        ),
    ]
