# Generated by Django 4.2.16 on 2026-04-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_executiontrace_project_id_executiontrace_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiontrace',
            name='dashboard_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='ID do relatório vinculado', null=True),
        ),
        migrations.AddField(
            model_name='executiontrace',
            name='estimated_cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Custo estimado em USD', max_digits=12),
        ),
        migrations.AddField(
            model_name='executiontrace',
            name='model_id',
            field=models.CharField(blank=True, help_text='ID do modelo utilizado', max_length=100),
        ),
    ]
